### ISSUE TITLE
Renaming `fct_collapse()`?

### ISSUE THREAD

**Issue by huftis** [hadley/forcats#13]
I find the name `fct_collapse()` somewhat misleading. For collapsing levels, one would typically use `fct_recode()`, **not** `fct_collapse()`.

Example: You have a factor for ‘Daily number of cigarettes smoked’, with these levels:

```
None
1–5
6–10
11–20
> 20
```

To *collapse* them into non-smoker, light smoker and heavy smoker (however you define those terms), or into non-smoker and smoker, you would use `fct_recode()`.

Suggestion: Rename `fct_collapse()` into `fct_lump()` or `fct_lump_other()`. This would also be consistent with its description: ‘lump rarest (or most common) levels into "other".‘

**Comment by huftis** [comment]
Yes, a `fct_collapse()` that did this would be very useful.

For an ever more powerful syntax, have a look at the `recode()` function in the `car` package:
http://www.rdocumentation.org/packages/car/versions/2.1-2/topics/recode
(Though this uses *strings* for specifying the recoding, which I dislike.)

**Comment by hadley** [comment]
Yeah, I'm familiar with `car::recode()` but I really don't like the string-based API.
