### ISSUE TITLE
Feature Request:  Sort text with combined character numeric values

### ISSUE THREAD

**Issue by billdenney** [hadley/forcats#15]
I work with factors that often contain text that mixes numeric and text data.  Often the data is related to dosing medicines, so it may look like:

```
"Drug A 1 mg"
"Drug B 1 mg"
"Drug A 10 mg"
"Drug B 10 mg"
"Drug A 3 mg"
"Drug B 3 mg"
```

I have a set of functions I use to sort this by separating the text and numeric parts and sort the character strings by parts.  As an example, the above would be split into the below parts (note the numbers are not quoted)

```
"Drug A ", 1, " mg"
"Drug B ", 1, " mg"
"Drug A ", 10, " mg"
"Drug B ", 10, " mg"
"Drug A ", 3, " mg"
"Drug B ", 3, " mg"
```

then sorted by each part separately either as a character or text, and I'd end up with the following for my ordered factor levels:

```
"Drug A 1 mg"
"Drug A 3 mg"
"Drug A 10 mg"
"Drug B 1 mg"
"Drug B 3 mg"
"Drug B 10 mg"
```

The code I use handles cases with an uneven number of groupings with un-aligned types of data (numeric vs. character) and with potentially missing data.  Would you be interested in these functions as an extension of the fct_reorder function?

**Comment by hadley** [comment]
Try https://cran.r-project.org/web/packages/naturalsort/index.html - but to me, it seems like a bad idea to store 3 variables worth of data in 1 variable
