### ISSUE TITLE
Feature request: Convert specfied levels into NA values

### ISSUE THREAD

**Issue by huftis** [hadley/forcats#17]
Sometimes missing data isn’t properly coded as `NA`. Here’s a feature request for a function to convert one or more specified levels into `NA` values (and remove the levels). Proposed code:

```r
fct_make_na = function(f, na_vals="NA") {
  f = forcats:::check_factor(f) # Also handle character vectors
  f[f %in% na_vals] = NA
  levs = levels(f)
  factor(f, levels = levs[!(levs %in% na_vals)])
}
```

Example:

```r
> x = c("foo","foo","(missing)", "bar", "unknown", "-", "baz")
> x = factor(x, levels=c(unique(x), "extra"))
> x
[1] foo       foo       (missing) bar       unknown   -         baz      
Levels: foo (missing) bar unknown - baz extra

> fct_make_na(x, na_vals=c("-", "(missing)", "unknown"))
[1] foo  foo  <NA> bar  <NA> <NA> baz 
Levels: foo bar baz extra
```

Note that the ‘missing’ levels are removed, but the `extra` level is retained, even if no element has the level `extra`.

**Comment by hadley** [comment]
My feeling is that missing value should remain an explicit level, so that they're automatically included in summaries, graphics, etc.  In that case, you can just use `fct_recode`
