### ISSUE TITLE
Turn specific levels into NA values

### ISSUE THREAD

**Issue by jeremystan** [hadley/forcats#20]
There is not an easy way to coerce factor levels into NAs. For example:

```{r}
> library(forcats)
> animals <- factor(c("dog", "cat", "missing"))
> fct_recode(animals, NA = "missing")
Error: unexpected '=' in "fct_recode(animals, NA ="
```

The desired effect can be achieved by making the desired levels explicit:

```{r}
> factor(animals, levels = c("dog", "cat"))
[1] dog  cat  <NA>
Levels: dog cat
```

Or by removing the offending level:

```{r}
> animals %>% factor(levels = setdiff(., "missing"))
[1] dog  cat  <NA>
Levels: dog cat
```

**Comment by hadley** [comment]
BTW in future PRs, you should include `Closes #20` so the issue automatically gets closed when the PR is merged.
