### ISSUE TITLE
Feature request: anonymise levels

### ISSUE THREAD

**Issue by jonocarroll** [hadley/forcats#22]
Often in real-world data a set of levels are identifying (licence number, SSN, etc...) and need to be anonymised prior to data release - could we have a re-leveling that takes in a common prefix (perhaps with some sensible default) or a hash function, shuffles the levels, then recodes them to anonymous levels? Internally, it's potentially a combination of `fct_shuffle()` and `fct_recode()` plus a way to generate the new levels.

Care needs to be taken that the new levels don't follow an [identifiable connecting pattern to the original levels](http://arstechnica.com/tech-policy/2014/06/poorly-anonymized-logs-reveal-nyc-cab-drivers-detailed-whereabouts/) (e.g. alphabetical -> sequential). `sample()` should take care of this just fine.

I'd do this as a PR but I get the feeling you're on a roll with the internal self-consistency you've got going.

**Comment by hadley** [comment]
Was that what you were thinking?

**Comment by jonocarroll** [comment]
Looks great and behaves as expected, thanks!

The only further addition I can think of would be to include (or allow) a prefix on the new factor names to distinguish them as anonymous factor levels rather than something that can potentially be accidentally processed as integer (not even sure that's possible, but considering edge cases). 

Prefix with `"anon"`? `"lvl"`?

**Comment by hadley** [comment]
I don't think there's an obvious default prefix, so I'll just make it an option.

**Comment by jonocarroll** [comment]
Beautiful. Thank you. This is going to be very handy.
