### ISSUE TITLE
create flags and create from flags

### ISSUE THREAD

**Issue by markdanese** [hadley/forcats#30]
For some situations, the categories are actual flag (0/1 variables, either INT or Logical) and one needs to take them and turn them into a single factor variable.  Sometimes one needs to go the other way.   This is actually a very specific implementation of dcast/melt and can be useful for going between modeling (each level is a dummy variable in a model) and ggplot.  Sometimes one also needs to combine some less commonly used levels into an "other" group when doing this transformation.

**Comment by hadley** [comment]
Can you give an example? What should happen if the values aren't actually unique? (i.e. there are multiple TRUEs in a row)

**Comment by markdanese** [comment]
It is just a simple transform of a factor to dummy variables
```
  num fac
1   1   a
2   2   b
3   3   c
4   4   d
5   5   e
```
becomes
```
  num fac a b c d e
1   1   a 1 0 0 0 0
2   2   b 0 1 0 0 0
3   3   c 0 0 1 0 0
4   4   d 0 0 0 1 0
5   5   e 0 0 0 0 1
```
Now that I think about it, one can just use factors in model formulas and it turns them into appropriate dummy variables behind the scenes.  I find working with factors for modeling to be a little challenging (changing the reference group).  Mostly this is because I avoid factors and changing the reference level, and I prefer to create my own dummy variables.  Creating factors with collapsed groups is also challenging.  But I think you have that handled already.

**Comment by njtierney** [comment]
Hmmm, a function to do this in a `tibble` would be handy. I've used `model.matrix`for when I was doing something funky with JAGS.

Here's a more reproducible example of what I think @markdanese is referring to:

``` r
df <- tibble::tibble(num = 1:5,
                     fac = letters[1:5])

df
#> # A tibble: 5 × 2
#>     num   fac
#>   <int> <chr>
#> 1     1     a
#> 2     2     b
#> 3     3     c
#> 4     4     d
#> 5     5     e

model.matrix(~ num + fac, df)
#>   (Intercept) num facb facc facd face
#> 1           1   1    0    0    0    0
#> 2           1   2    1    0    0    0
#> 3           1   3    0    1    0    0
#> 4           1   4    0    0    1    0
#> 5           1   5    0    0    0    1
#> attr(,"assign")
#> [1] 0 1 2 2 2 2
#> attr(,"contrasts")
#> attr(,"contrasts")$fac
#> [1] "contr.treatment"
```

**Comment by markdanese** [comment]
It is a good point.  One problem with this is that if you want all of the dummy variables, you have play with contrasts and set the contrast for the factor to FALSE.

```
df <- data.frame(num = 1:5, fac = factor(letters[1:5]))
f$fac <- contrasts(df$fac, contrasts = FALSE)
model.matrix(~ num + fac, df)
```

This returns the following, which also drops the factor variable.  And, of course, it adds an intercept which isn't useful in this case.

```
  (Intercept) num faca facb facc facd face
1           1   1    1    0    0    0    0
2           1   2    0    1    0    0    0
3           1   3    0    0    1    0    0
4           1   4    0    0    0    1    0
5           1   5    0    0    0    0    1
attr(,"assign")
[1] 0 1 2 2 2 2 2
```

**Comment by huftis** [comment]
There are already several packages for handling dummy variables, e.g. [dummies](https://cran.r-project.org/web/packages/dummies/index.html) and [dummy](https://cran.r-project.org/web/packages/dummy/index.html). They convert factors to dummy variables. For the reverse operation, you can [use simple matrix multiplication](http://r.789695.n4.nabble.com/R-how-to-convert-multiple-dummy-variables-to-1-factor-variable-td810654.html#a810662).

**Comment by markdanese** [comment]
So, I guess the question is whether this functionality belongs in the forcats package.  I don't often look for packages with such specific functionality (clearly my loss, of course).  The fact that there are 2 packages suggests that others have similar issues.  Obviously up to Hadley as to whether it belongs in the package.  Either way, I can make do with my own code or the packages I just learned about.  (@huftis -- thanks for sharing those packages)

**Comment by njtierney** [comment]
Thanks for that, @huftis, interesting to note that there are specialised packages for this!

I've only spent a couple of minutes looking at these packages, but I can't quite reproduce what we want from the above, but perhaps you have a better idea. I'm probably missing something really obvious.

``` r
df <- tibble::tibble(num = 1:5,
                     fac = letters[1:5])

df
#> # A tibble: 5 × 2
#>     num   fac
#>   <int> <chr>
#> 1     1     a
#> 2     2     b
#> 3     3     c
#> 4     4     d
#> 5     5     e

model.matrix(~ num + fac, df)
#>   (Intercept) num facb facc facd face
#> 1           1   1    0    0    0    0
#> 2           1   2    1    0    0    0
#> 3           1   3    0    1    0    0
#> 4           1   4    0    0    1    0
#> 5           1   5    0    0    0    1
#> attr(,"assign")
#> [1] 0 1 2 2 2 2
#> attr(,"contrasts")
#> attr(,"contrasts")$fac
#> [1] "contr.treatment"

# using `dummy` -------------------------------------------------------
# install.packages("dummy")
dummy::dummy(df)
#>   fac_a fac_b fac_c fac_d fac_e
#> 1     1     0     0     0     0
#> 2     0     1     0     0     0
#> 3     0     0     1     0     0
#> 4     0     0     0     1     0
#> 5     0     0     0     0     1

# using `dummies` -----------------------------------------------------
# install.packages("dummies")
dummies::dummy.data.frame(df, all = FALSE)
#> Error in if (nm %in% names || (is.null(names) && (dummy.classes == "ALL" || : missing value where TRUE/FALSE needed
dummies::dummy.data.frame(df, dummy.classes = "ALL")
#> Error in sort.list(y): 'x' must be atomic for 'sort.list'
#> Have you called 'sort' on a list?

dummies::dummy(df)
#> Error in sort.list(y): 'x' must be atomic for 'sort.list'
#> Have you called 'sort' on a list?
dummies::get.dummy(df, name = num)
#> Error in dummies::get.dummy(df, name = num): object 'num' not found
dummies::get.dummy(df, name = "num")
#> # A tibble: 5 × 0

```

Of course, still up to Hadley whether this belongs in the package!

**Comment by hadley** [comment]
It doesn't feel quite in scope for forcats to me. It doesn't seem like the other functions

**Comment by huftis** [comment]
@njtierney For this data set,

```r
df <- data.frame(num = 1:5,
                 fac = factor(letters[1:5]))
```

the following three methods of generating dummy variables work fine, and give essentially identical results:

```r
model.matrix(~ fac - 1, df)
dummy::dummy(df)
dummies::dummy.data.frame(df, all = FALSE)
```

Or if you want to keep the non-dummy variables:

```r
model.matrix(~ num + fac - 1, df)
dummies::dummy.data.frame(df)
```
