### ISSUE TITLE
wrap text on factor levels

### ISSUE THREAD

**Issue by nicholas-vogt** [hadley/forcats#31]
Hi Hadley, I'm really enjoying using the package. Thanks for making it! 

I routinely find the need to wrap text on my factors before plotting. Sometimes the factor levels are long and extend the legend margins. 

Here's an example of what I mean: ![Original](http://imgur.com/0lDspBP]) compared to ![wrapped text](http://imgur.com/lRB3Xlk).

Is this something you'd be interested in adding? I'd be happy to make a pull request.

**Comment by hadley** [comment]
That feels out of scope for forcats to me, given that you can already get very close with `stringr::str_wrap`.  It might be worth filing a bug with stringr/stringi to request that string operations on factors instead operate on the levels.
