### ISSUE TITLE
fct_recode and NULL vector

### ISSUE THREAD

**Issue by jwijffels** [hadley/forcats#33]
Currently fct_recode does this if you give a vector of values for NULL

```
x <- factor(c("apple", "bear", "banana", "dear"))
fct_recode(x, NULL = c("apple", "dear"), fruit = "banana")

[1] NULL1 bear  fruit NULL2
Levels: NULL1 fruit bear NULL2
```

If you want to put several levels to NULL, it appears that you should do this.
`fct_recode(x, NULL = "apple", NULL = "dear", fruit = "banana")`

Wouldn't it make a lot more sense that this just works?
`fct_recode(x, NULL = c("apple", "dear"), fruit = "banana")`

**Comment by hadley** [comment]
That's the difference between `fct_recode` and `fct_collapse`
